#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 125
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 48
#define ALIAS_COUNT 1
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 11

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_type = 2,
  anon_sym_EQ = 3,
  sym_export_modifier = 4,
  anon_sym_LT = 5,
  anon_sym_COMMA = 6,
  anon_sym_GT = 7,
  anon_sym_DOT = 8,
  anon_sym_QMARK = 9,
  anon_sym_AMP = 10,
  anon_sym_PIPE = 11,
  anon_sym_EQ_GT = 12,
  anon_sym_LPAREN = 13,
  anon_sym_RPAREN = 14,
  anon_sym_LBRACE = 15,
  anon_sym_RBRACE = 16,
  anon_sym_COLON = 17,
  sym_self = 18,
  sym_line_comment = 19,
  sym_doc_comment = 20,
  sym_block_comment = 21,
  sym_source_file = 22,
  sym_type_definition = 23,
  sym_generic_parameters = 24,
  sym_generic_parameter = 25,
  sym_generic_arguments = 26,
  sym__type = 27,
  sym__type_path = 28,
  sym_qualified_type = 29,
  sym_generic_type = 30,
  sym_optional_type = 31,
  sym_intersection_type = 32,
  sym_union_type = 33,
  sym_function_type = 34,
  sym_parenthesized_type = 35,
  sym_object_type = 36,
  sym_field = 37,
  sym_method = 38,
  sym_parameters = 39,
  sym_parameter = 40,
  sym__type_identifier = 41,
  aux_sym_source_file_repeat1 = 42,
  aux_sym_generic_parameters_repeat1 = 43,
  aux_sym_generic_arguments_repeat1 = 44,
  aux_sym_qualified_type_repeat1 = 45,
  aux_sym_object_type_repeat1 = 46,
  aux_sym_parameters_repeat1 = 47,
  alias_sym_type_identifier = 48,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_type] = "type",
  [anon_sym_EQ] = "=",
  [sym_export_modifier] = "export_modifier",
  [anon_sym_LT] = "<",
  [anon_sym_COMMA] = ",",
  [anon_sym_GT] = ">",
  [anon_sym_DOT] = ".",
  [anon_sym_QMARK] = "\?",
  [anon_sym_AMP] = "&",
  [anon_sym_PIPE] = "|",
  [anon_sym_EQ_GT] = "=>",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [sym_self] = "self",
  [sym_line_comment] = "line_comment",
  [sym_doc_comment] = "doc_comment",
  [sym_block_comment] = "block_comment",
  [sym_source_file] = "source_file",
  [sym_type_definition] = "type_definition",
  [sym_generic_parameters] = "generic_parameters",
  [sym_generic_parameter] = "generic_parameter",
  [sym_generic_arguments] = "generic_arguments",
  [sym__type] = "_type",
  [sym__type_path] = "_type_path",
  [sym_qualified_type] = "qualified_type",
  [sym_generic_type] = "generic_type",
  [sym_optional_type] = "optional_type",
  [sym_intersection_type] = "intersection_type",
  [sym_union_type] = "union_type",
  [sym_function_type] = "function_type",
  [sym_parenthesized_type] = "parenthesized_type",
  [sym_object_type] = "object_type",
  [sym_field] = "field",
  [sym_method] = "method",
  [sym_parameters] = "parameters",
  [sym_parameter] = "parameter",
  [sym__type_identifier] = "_type_identifier",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_generic_parameters_repeat1] = "generic_parameters_repeat1",
  [aux_sym_generic_arguments_repeat1] = "generic_arguments_repeat1",
  [aux_sym_qualified_type_repeat1] = "qualified_type_repeat1",
  [aux_sym_object_type_repeat1] = "object_type_repeat1",
  [aux_sym_parameters_repeat1] = "parameters_repeat1",
  [alias_sym_type_identifier] = "type_identifier",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_export_modifier] = sym_export_modifier,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_self] = sym_self,
  [sym_line_comment] = sym_line_comment,
  [sym_doc_comment] = sym_doc_comment,
  [sym_block_comment] = sym_block_comment,
  [sym_source_file] = sym_source_file,
  [sym_type_definition] = sym_type_definition,
  [sym_generic_parameters] = sym_generic_parameters,
  [sym_generic_parameter] = sym_generic_parameter,
  [sym_generic_arguments] = sym_generic_arguments,
  [sym__type] = sym__type,
  [sym__type_path] = sym__type_path,
  [sym_qualified_type] = sym_qualified_type,
  [sym_generic_type] = sym_generic_type,
  [sym_optional_type] = sym_optional_type,
  [sym_intersection_type] = sym_intersection_type,
  [sym_union_type] = sym_union_type,
  [sym_function_type] = sym_function_type,
  [sym_parenthesized_type] = sym_parenthesized_type,
  [sym_object_type] = sym_object_type,
  [sym_field] = sym_field,
  [sym_method] = sym_method,
  [sym_parameters] = sym_parameters,
  [sym_parameter] = sym_parameter,
  [sym__type_identifier] = sym__type_identifier,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_generic_parameters_repeat1] = aux_sym_generic_parameters_repeat1,
  [aux_sym_generic_arguments_repeat1] = aux_sym_generic_arguments_repeat1,
  [aux_sym_qualified_type_repeat1] = aux_sym_qualified_type_repeat1,
  [aux_sym_object_type_repeat1] = aux_sym_object_type_repeat1,
  [aux_sym_parameters_repeat1] = aux_sym_parameters_repeat1,
  [alias_sym_type_identifier] = alias_sym_type_identifier,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_export_modifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_self] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_doc_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_type_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_generic_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_generic_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_generic_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym__type_path] = {
    .visible = false,
    .named = true,
  },
  [sym_qualified_type] = {
    .visible = true,
    .named = true,
  },
  [sym_generic_type] = {
    .visible = true,
    .named = true,
  },
  [sym_optional_type] = {
    .visible = true,
    .named = true,
  },
  [sym_intersection_type] = {
    .visible = true,
    .named = true,
  },
  [sym_union_type] = {
    .visible = true,
    .named = true,
  },
  [sym_function_type] = {
    .visible = true,
    .named = true,
  },
  [sym_parenthesized_type] = {
    .visible = true,
    .named = true,
  },
  [sym_object_type] = {
    .visible = true,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym_method] = {
    .visible = true,
    .named = true,
  },
  [sym_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym__type_identifier] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_generic_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_generic_arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_qualified_type_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_object_type_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_type_identifier] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_name = 1,
  field_return = 2,
  field_type = 3,
  field_value = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
  [field_return] = "return",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [2] = {.index = 0, .length = 2},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 1},
  [7] = {.index = 8, .length = 2},
  [8] = {.index = 10, .length = 2},
  [9] = {.index = 12, .length = 2},
  [10] = {.index = 14, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
    {field_value, 3},
  [2] =
    {field_name, 0},
  [3] =
    {field_name, 1},
    {field_value, 4},
  [5] =
    {field_name, 2},
    {field_value, 4},
  [7] =
    {field_return, 2},
  [8] =
    {field_name, 2},
    {field_value, 5},
  [10] =
    {field_name, 0},
    {field_type, 2},
  [12] =
    {field_name, 0},
    {field_type, 3},
  [14] =
    {field_name, 0},
    {field_return, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = alias_sym_type_identifier,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 7,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 10,
  [20] = 8,
  [21] = 4,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 22,
  [41] = 24,
  [42] = 25,
  [43] = 43,
  [44] = 27,
  [45] = 23,
  [46] = 26,
  [47] = 37,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 33,
  [57] = 29,
  [58] = 30,
  [59] = 31,
  [60] = 32,
  [61] = 28,
  [62] = 34,
  [63] = 35,
  [64] = 36,
  [65] = 65,
  [66] = 38,
  [67] = 39,
  [68] = 68,
  [69] = 68,
  [70] = 48,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 73,
  [81] = 71,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 87,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 88,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 104,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 116,
  [124] = 124,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      ADVANCE_MAP(
        '&', 15,
        '(', 18,
        ')', 19,
        ',', 11,
        '-', 2,
        '.', 13,
        ':', 22,
        '<', 10,
        '=', 9,
        '>', 12,
        '?', 14,
        '{', 20,
        '|', 16,
        '}', 21,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 1:
      if (lookahead == ',') ADVANCE(11);
      if (lookahead == '-') ADVANCE(2);
      if (lookahead == ':') ADVANCE(22);
      if (lookahead == '=') ADVANCE(3);
      if (lookahead == '}') ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 2:
      if (lookahead == '-') ADVANCE(26);
      END_STATE();
    case 3:
      if (lookahead == '>') ADVANCE(17);
      END_STATE();
    case 4:
      if (lookahead == ']') ADVANCE(31);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == ']') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (eof) ADVANCE(7);
      ADVANCE_MAP(
        '&', 15,
        ')', 19,
        ',', 11,
        '-', 2,
        '.', 13,
        '<', 10,
        '=', 8,
        '>', 12,
        '?', 14,
        '|', 16,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '>') ADVANCE(17);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead == '\n') ADVANCE(5);
      if (lookahead == ']') ADVANCE(30);
      if (lookahead != 0) ADVANCE(25);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead == '\n') ADVANCE(5);
      if (lookahead == ']') ADVANCE(24);
      if (lookahead != 0) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead == '-') ADVANCE(29);
      if (lookahead == '[') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(28);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead == '[') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(28);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_doc_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_block_comment);
      if (lookahead == '\n') ADVANCE(5);
      if (lookahead == ']') ADVANCE(30);
      if (lookahead != 0) ADVANCE(25);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_block_comment);
      if (lookahead == ']') ADVANCE(31);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'e') ADVANCE(1);
      if (lookahead == 's') ADVANCE(2);
      if (lookahead == 't') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'x') ADVANCE(4);
      END_STATE();
    case 2:
      if (lookahead == 'e') ADVANCE(5);
      END_STATE();
    case 3:
      if (lookahead == 'y') ADVANCE(6);
      END_STATE();
    case 4:
      if (lookahead == 'p') ADVANCE(7);
      END_STATE();
    case 5:
      if (lookahead == 'l') ADVANCE(8);
      END_STATE();
    case 6:
      if (lookahead == 'p') ADVANCE(9);
      END_STATE();
    case 7:
      if (lookahead == 'o') ADVANCE(10);
      END_STATE();
    case 8:
      if (lookahead == 'f') ADVANCE(11);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(12);
      END_STATE();
    case 10:
      if (lookahead == 'r') ADVANCE(13);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_self);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 13:
      if (lookahead == 't') ADVANCE(14);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_export_modifier);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 6},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 6},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 6},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 1},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 6},
  [119] = {.lex_state = 6},
  [120] = {.lex_state = 6},
  [121] = {.lex_state = 6},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 1},
  [124] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_export_modifier] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_self] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_comment] = ACTIONS(5),
    [sym_block_comment] = ACTIONS(5),
  },
  [1] = {
    [sym_source_file] = STATE(124),
    [sym_type_definition] = STATE(78),
    [aux_sym_source_file_repeat1] = STATE(78),
    [ts_builtin_sym_end] = ACTIONS(7),
    [anon_sym_type] = ACTIONS(9),
    [sym_export_modifier] = ACTIONS(11),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_comment] = ACTIONS(5),
    [sym_block_comment] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_RPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      sym_self,
    STATE(22), 1,
      sym__type_identifier,
    STATE(69), 1,
      sym__type,
    STATE(98), 1,
      sym_parameter,
    STATE(116), 1,
      sym_parameters,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    STATE(26), 2,
      sym__type_path,
      sym_qualified_type,
    STATE(33), 7,
      sym_generic_type,
      sym_optional_type,
      sym_intersection_type,
      sym_union_type,
      sym_function_type,
      sym_parenthesized_type,
      sym_object_type,
  [48] = 13,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_RPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      sym_self,
    STATE(22), 1,
      sym__type_identifier,
    STATE(68), 1,
      sym__type,
    STATE(98), 1,
      sym_parameter,
    STATE(116), 1,
      sym_parameters,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    STATE(26), 2,
      sym__type_path,
      sym_qualified_type,
    STATE(33), 7,
      sym_generic_type,
      sym_optional_type,
      sym_intersection_type,
      sym_union_type,
      sym_function_type,
      sym_parenthesized_type,
      sym_object_type,
  [96] = 10,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      sym_identifier,
    STATE(22), 1,
      sym__type_identifier,
    STATE(48), 1,
      sym__type,
    STATE(116), 1,
      sym_parameters,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    STATE(26), 2,
      sym__type_path,
      sym_qualified_type,
    STATE(33), 7,
      sym_generic_type,
      sym_optional_type,
      sym_intersection_type,
      sym_union_type,
      sym_function_type,
      sym_parenthesized_type,
      sym_object_type,
  [135] = 10,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      sym_identifier,
    STATE(22), 1,
      sym__type_identifier,
    STATE(53), 1,
      sym__type,
    STATE(116), 1,
      sym_parameters,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    STATE(26), 2,
      sym__type_path,
      sym_qualified_type,
    STATE(33), 7,
      sym_generic_type,
      sym_optional_type,
      sym_intersection_type,
      sym_union_type,
      sym_function_type,
      sym_parenthesized_type,
      sym_object_type,
  [174] = 10,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      sym_identifier,
    STATE(22), 1,
      sym__type_identifier,
    STATE(65), 1,
      sym__type,
    STATE(116), 1,
      sym_parameters,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    STATE(26), 2,
      sym__type_path,
      sym_qualified_type,
    STATE(33), 7,
      sym_generic_type,
      sym_optional_type,
      sym_intersection_type,
      sym_union_type,
      sym_function_type,
      sym_parenthesized_type,
      sym_object_type,
  [213] = 10,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      sym_identifier,
    STATE(22), 1,
      sym__type_identifier,
    STATE(36), 1,
      sym__type,
    STATE(116), 1,
      sym_parameters,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    STATE(26), 2,
      sym__type_path,
      sym_qualified_type,
    STATE(33), 7,
      sym_generic_type,
      sym_optional_type,
      sym_intersection_type,
      sym_union_type,
      sym_function_type,
      sym_parenthesized_type,
      sym_object_type,
  [252] = 10,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      sym_identifier,
    STATE(22), 1,
      sym__type_identifier,
    STATE(35), 1,
      sym__type,
    STATE(116), 1,
      sym_parameters,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    STATE(26), 2,
      sym__type_path,
      sym_qualified_type,
    STATE(33), 7,
      sym_generic_type,
      sym_optional_type,
      sym_intersection_type,
      sym_union_type,
      sym_function_type,
      sym_parenthesized_type,
      sym_object_type,
  [291] = 10,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      sym_identifier,
    STATE(22), 1,
      sym__type_identifier,
    STATE(49), 1,
      sym__type,
    STATE(116), 1,
      sym_parameters,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    STATE(26), 2,
      sym__type_path,
      sym_qualified_type,
    STATE(33), 7,
      sym_generic_type,
      sym_optional_type,
      sym_intersection_type,
      sym_union_type,
      sym_function_type,
      sym_parenthesized_type,
      sym_object_type,
  [330] = 10,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      sym_identifier,
    STATE(22), 1,
      sym__type_identifier,
    STATE(34), 1,
      sym__type,
    STATE(116), 1,
      sym_parameters,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    STATE(26), 2,
      sym__type_path,
      sym_qualified_type,
    STATE(33), 7,
      sym_generic_type,
      sym_optional_type,
      sym_intersection_type,
      sym_union_type,
      sym_function_type,
      sym_parenthesized_type,
      sym_object_type,
  [369] = 10,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      sym_identifier,
    STATE(22), 1,
      sym__type_identifier,
    STATE(50), 1,
      sym__type,
    STATE(116), 1,
      sym_parameters,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    STATE(26), 2,
      sym__type_path,
      sym_qualified_type,
    STATE(33), 7,
      sym_generic_type,
      sym_optional_type,
      sym_intersection_type,
      sym_union_type,
      sym_function_type,
      sym_parenthesized_type,
      sym_object_type,
  [408] = 10,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      sym_identifier,
    STATE(22), 1,
      sym__type_identifier,
    STATE(51), 1,
      sym__type,
    STATE(116), 1,
      sym_parameters,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    STATE(26), 2,
      sym__type_path,
      sym_qualified_type,
    STATE(33), 7,
      sym_generic_type,
      sym_optional_type,
      sym_intersection_type,
      sym_union_type,
      sym_function_type,
      sym_parenthesized_type,
      sym_object_type,
  [447] = 10,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    STATE(40), 1,
      sym__type_identifier,
    STATE(52), 1,
      sym__type,
    STATE(123), 1,
      sym_parameters,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    STATE(46), 2,
      sym__type_path,
      sym_qualified_type,
    STATE(56), 7,
      sym_generic_type,
      sym_optional_type,
      sym_intersection_type,
      sym_union_type,
      sym_function_type,
      sym_parenthesized_type,
      sym_object_type,
  [486] = 10,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      sym_identifier,
    STATE(22), 1,
      sym__type_identifier,
    STATE(79), 1,
      sym__type,
    STATE(116), 1,
      sym_parameters,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    STATE(26), 2,
      sym__type_path,
      sym_qualified_type,
    STATE(33), 7,
      sym_generic_type,
      sym_optional_type,
      sym_intersection_type,
      sym_union_type,
      sym_function_type,
      sym_parenthesized_type,
      sym_object_type,
  [525] = 10,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    STATE(40), 1,
      sym__type_identifier,
    STATE(64), 1,
      sym__type,
    STATE(123), 1,
      sym_parameters,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    STATE(46), 2,
      sym__type_path,
      sym_qualified_type,
    STATE(56), 7,
      sym_generic_type,
      sym_optional_type,
      sym_intersection_type,
      sym_union_type,
      sym_function_type,
      sym_parenthesized_type,
      sym_object_type,
  [564] = 10,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      sym_identifier,
    STATE(22), 1,
      sym__type_identifier,
    STATE(76), 1,
      sym__type,
    STATE(116), 1,
      sym_parameters,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    STATE(26), 2,
      sym__type_path,
      sym_qualified_type,
    STATE(33), 7,
      sym_generic_type,
      sym_optional_type,
      sym_intersection_type,
      sym_union_type,
      sym_function_type,
      sym_parenthesized_type,
      sym_object_type,
  [603] = 10,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    STATE(40), 1,
      sym__type_identifier,
    STATE(54), 1,
      sym__type,
    STATE(123), 1,
      sym_parameters,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    STATE(46), 2,
      sym__type_path,
      sym_qualified_type,
    STATE(56), 7,
      sym_generic_type,
      sym_optional_type,
      sym_intersection_type,
      sym_union_type,
      sym_function_type,
      sym_parenthesized_type,
      sym_object_type,
  [642] = 10,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    STATE(40), 1,
      sym__type_identifier,
    STATE(55), 1,
      sym__type,
    STATE(123), 1,
      sym_parameters,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    STATE(46), 2,
      sym__type_path,
      sym_qualified_type,
    STATE(56), 7,
      sym_generic_type,
      sym_optional_type,
      sym_intersection_type,
      sym_union_type,
      sym_function_type,
      sym_parenthesized_type,
      sym_object_type,
  [681] = 10,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    STATE(40), 1,
      sym__type_identifier,
    STATE(62), 1,
      sym__type,
    STATE(123), 1,
      sym_parameters,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    STATE(46), 2,
      sym__type_path,
      sym_qualified_type,
    STATE(56), 7,
      sym_generic_type,
      sym_optional_type,
      sym_intersection_type,
      sym_union_type,
      sym_function_type,
      sym_parenthesized_type,
      sym_object_type,
  [720] = 10,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    STATE(40), 1,
      sym__type_identifier,
    STATE(63), 1,
      sym__type,
    STATE(123), 1,
      sym_parameters,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    STATE(46), 2,
      sym__type_path,
      sym_qualified_type,
    STATE(56), 7,
      sym_generic_type,
      sym_optional_type,
      sym_intersection_type,
      sym_union_type,
      sym_function_type,
      sym_parenthesized_type,
      sym_object_type,
  [759] = 10,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      sym_identifier,
    STATE(22), 1,
      sym__type_identifier,
    STATE(70), 1,
      sym__type,
    STATE(116), 1,
      sym_parameters,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    STATE(26), 2,
      sym__type_path,
      sym_qualified_type,
    STATE(33), 7,
      sym_generic_type,
      sym_optional_type,
      sym_intersection_type,
      sym_union_type,
      sym_function_type,
      sym_parenthesized_type,
      sym_object_type,
  [798] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(33), 1,
      anon_sym_DOT,
    STATE(24), 1,
      aux_sym_qualified_type_repeat1,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(31), 10,
      ts_builtin_sym_end,
      anon_sym_type,
      sym_export_modifier,
      anon_sym_LT,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_RPAREN,
  [824] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(35), 12,
      ts_builtin_sym_end,
      anon_sym_type,
      anon_sym_EQ,
      sym_export_modifier,
      anon_sym_LT,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_DOT,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_RPAREN,
  [846] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(33), 1,
      anon_sym_DOT,
    STATE(25), 1,
      aux_sym_qualified_type_repeat1,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(37), 10,
      ts_builtin_sym_end,
      anon_sym_type,
      sym_export_modifier,
      anon_sym_LT,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_RPAREN,
  [872] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(41), 1,
      anon_sym_DOT,
    STATE(25), 1,
      aux_sym_qualified_type_repeat1,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(39), 10,
      ts_builtin_sym_end,
      anon_sym_type,
      sym_export_modifier,
      anon_sym_LT,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_RPAREN,
  [898] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(46), 1,
      anon_sym_LT,
    STATE(31), 1,
      sym_generic_arguments,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(44), 9,
      ts_builtin_sym_end,
      anon_sym_type,
      sym_export_modifier,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_RPAREN,
  [923] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(39), 11,
      ts_builtin_sym_end,
      anon_sym_type,
      sym_export_modifier,
      anon_sym_LT,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_DOT,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_RPAREN,
  [944] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(48), 9,
      ts_builtin_sym_end,
      anon_sym_type,
      sym_export_modifier,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_RPAREN,
  [963] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(50), 9,
      ts_builtin_sym_end,
      anon_sym_type,
      sym_export_modifier,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_RPAREN,
  [982] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(52), 9,
      ts_builtin_sym_end,
      anon_sym_type,
      sym_export_modifier,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_RPAREN,
  [1001] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(54), 9,
      ts_builtin_sym_end,
      anon_sym_type,
      sym_export_modifier,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_RPAREN,
  [1020] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(56), 9,
      ts_builtin_sym_end,
      anon_sym_type,
      sym_export_modifier,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_RPAREN,
  [1039] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(44), 9,
      ts_builtin_sym_end,
      anon_sym_type,
      sym_export_modifier,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_RPAREN,
  [1058] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(60), 1,
      anon_sym_QMARK,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(58), 8,
      ts_builtin_sym_end,
      anon_sym_type,
      sym_export_modifier,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_RPAREN,
  [1079] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(60), 1,
      anon_sym_QMARK,
    ACTIONS(64), 1,
      anon_sym_AMP,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(62), 7,
      ts_builtin_sym_end,
      anon_sym_type,
      sym_export_modifier,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_PIPE,
      anon_sym_RPAREN,
  [1102] = 6,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(60), 1,
      anon_sym_QMARK,
    ACTIONS(64), 1,
      anon_sym_AMP,
    ACTIONS(68), 1,
      anon_sym_PIPE,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(66), 6,
      ts_builtin_sym_end,
      anon_sym_type,
      sym_export_modifier,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_RPAREN,
  [1127] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(70), 9,
      ts_builtin_sym_end,
      anon_sym_type,
      sym_export_modifier,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_RPAREN,
  [1146] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(72), 9,
      ts_builtin_sym_end,
      anon_sym_type,
      sym_export_modifier,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_RPAREN,
  [1165] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(74), 9,
      ts_builtin_sym_end,
      anon_sym_type,
      sym_export_modifier,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_RPAREN,
  [1184] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(76), 1,
      anon_sym_DOT,
    STATE(41), 1,
      aux_sym_qualified_type_repeat1,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(31), 7,
      anon_sym_LT,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      sym_identifier,
  [1207] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(76), 1,
      anon_sym_DOT,
    STATE(42), 1,
      aux_sym_qualified_type_repeat1,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(37), 7,
      anon_sym_LT,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      sym_identifier,
  [1230] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(78), 1,
      anon_sym_DOT,
    STATE(42), 1,
      aux_sym_qualified_type_repeat1,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(39), 7,
      anon_sym_LT,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      sym_identifier,
  [1253] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(81), 1,
      anon_sym_QMARK,
    ACTIONS(84), 1,
      anon_sym_COLON,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(35), 6,
      anon_sym_LT,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_RPAREN,
  [1275] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(39), 8,
      anon_sym_LT,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      sym_identifier,
  [1293] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(35), 8,
      anon_sym_LT,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      sym_identifier,
  [1311] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(86), 1,
      anon_sym_LT,
    STATE(59), 1,
      sym_generic_arguments,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(44), 6,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      sym_identifier,
  [1333] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(70), 6,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      sym_identifier,
  [1349] = 8,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(60), 1,
      anon_sym_QMARK,
    ACTIONS(64), 1,
      anon_sym_AMP,
    ACTIONS(68), 1,
      anon_sym_PIPE,
    ACTIONS(88), 1,
      anon_sym_COMMA,
    ACTIONS(90), 1,
      anon_sym_GT,
    STATE(101), 1,
      aux_sym_generic_arguments_repeat1,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
  [1375] = 6,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(60), 1,
      anon_sym_QMARK,
    ACTIONS(64), 1,
      anon_sym_AMP,
    ACTIONS(68), 1,
      anon_sym_PIPE,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(92), 3,
      ts_builtin_sym_end,
      anon_sym_type,
      sym_export_modifier,
  [1397] = 6,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(60), 1,
      anon_sym_QMARK,
    ACTIONS(64), 1,
      anon_sym_AMP,
    ACTIONS(68), 1,
      anon_sym_PIPE,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(94), 3,
      ts_builtin_sym_end,
      anon_sym_type,
      sym_export_modifier,
  [1419] = 6,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(60), 1,
      anon_sym_QMARK,
    ACTIONS(64), 1,
      anon_sym_AMP,
    ACTIONS(68), 1,
      anon_sym_PIPE,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(96), 3,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_RPAREN,
  [1441] = 7,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(100), 1,
      anon_sym_COMMA,
    ACTIONS(102), 1,
      anon_sym_QMARK,
    ACTIONS(104), 1,
      anon_sym_AMP,
    ACTIONS(106), 1,
      anon_sym_PIPE,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(98), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [1465] = 6,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(60), 1,
      anon_sym_QMARK,
    ACTIONS(64), 1,
      anon_sym_AMP,
    ACTIONS(68), 1,
      anon_sym_PIPE,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(108), 3,
      ts_builtin_sym_end,
      anon_sym_type,
      sym_export_modifier,
  [1487] = 7,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(102), 1,
      anon_sym_QMARK,
    ACTIONS(104), 1,
      anon_sym_AMP,
    ACTIONS(106), 1,
      anon_sym_PIPE,
    ACTIONS(112), 1,
      anon_sym_COMMA,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(110), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [1511] = 7,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(102), 1,
      anon_sym_QMARK,
    ACTIONS(104), 1,
      anon_sym_AMP,
    ACTIONS(106), 1,
      anon_sym_PIPE,
    ACTIONS(116), 1,
      anon_sym_COMMA,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(114), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [1535] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(44), 6,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      sym_identifier,
  [1551] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(50), 6,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      sym_identifier,
  [1567] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(52), 6,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      sym_identifier,
  [1583] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(54), 6,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      sym_identifier,
  [1599] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(56), 6,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      sym_identifier,
  [1615] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(48), 6,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      sym_identifier,
  [1631] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(102), 1,
      anon_sym_QMARK,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(58), 5,
      anon_sym_COMMA,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      sym_identifier,
  [1649] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(102), 1,
      anon_sym_QMARK,
    ACTIONS(104), 1,
      anon_sym_AMP,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(62), 4,
      anon_sym_COMMA,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      sym_identifier,
  [1669] = 6,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(102), 1,
      anon_sym_QMARK,
    ACTIONS(104), 1,
      anon_sym_AMP,
    ACTIONS(106), 1,
      anon_sym_PIPE,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(66), 3,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      sym_identifier,
  [1691] = 6,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(60), 1,
      anon_sym_QMARK,
    ACTIONS(64), 1,
      anon_sym_AMP,
    ACTIONS(68), 1,
      anon_sym_PIPE,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(118), 3,
      ts_builtin_sym_end,
      anon_sym_type,
      sym_export_modifier,
  [1713] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(72), 6,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      sym_identifier,
  [1729] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(74), 6,
      anon_sym_COMMA,
      anon_sym_QMARK,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      sym_identifier,
  [1745] = 8,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(60), 1,
      anon_sym_QMARK,
    ACTIONS(64), 1,
      anon_sym_AMP,
    ACTIONS(68), 1,
      anon_sym_PIPE,
    ACTIONS(88), 1,
      anon_sym_COMMA,
    ACTIONS(120), 1,
      anon_sym_RPAREN,
    STATE(87), 1,
      aux_sym_generic_arguments_repeat1,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
  [1771] = 8,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(60), 1,
      anon_sym_QMARK,
    ACTIONS(64), 1,
      anon_sym_AMP,
    ACTIONS(68), 1,
      anon_sym_PIPE,
    ACTIONS(88), 1,
      anon_sym_COMMA,
    ACTIONS(122), 1,
      anon_sym_RPAREN,
    STATE(91), 1,
      aux_sym_generic_arguments_repeat1,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
  [1797] = 8,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(60), 1,
      anon_sym_QMARK,
    ACTIONS(64), 1,
      anon_sym_AMP,
    ACTIONS(68), 1,
      anon_sym_PIPE,
    ACTIONS(88), 1,
      anon_sym_COMMA,
    ACTIONS(124), 1,
      anon_sym_GT,
    STATE(88), 1,
      aux_sym_generic_arguments_repeat1,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
  [1823] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(126), 1,
      sym_identifier,
    ACTIONS(128), 1,
      anon_sym_RBRACE,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    STATE(74), 3,
      sym_field,
      sym_method,
      aux_sym_object_type_repeat1,
  [1842] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(130), 5,
      anon_sym_COMMA,
      anon_sym_EQ_GT,
      anon_sym_RBRACE,
      anon_sym_COLON,
      sym_identifier,
  [1857] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(126), 1,
      sym_identifier,
    ACTIONS(132), 1,
      anon_sym_RBRACE,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    STATE(81), 3,
      sym_field,
      sym_method,
      aux_sym_object_type_repeat1,
  [1876] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(134), 1,
      sym_identifier,
    ACTIONS(137), 1,
      anon_sym_RBRACE,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    STATE(74), 3,
      sym_field,
      sym_method,
      aux_sym_object_type_repeat1,
  [1895] = 6,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(139), 1,
      ts_builtin_sym_end,
    ACTIONS(141), 1,
      anon_sym_type,
    ACTIONS(144), 1,
      sym_export_modifier,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    STATE(75), 2,
      sym_type_definition,
      aux_sym_source_file_repeat1,
  [1916] = 6,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(60), 1,
      anon_sym_QMARK,
    ACTIONS(64), 1,
      anon_sym_AMP,
    ACTIONS(68), 1,
      anon_sym_PIPE,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(147), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1937] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(149), 5,
      anon_sym_COMMA,
      anon_sym_EQ_GT,
      anon_sym_RBRACE,
      anon_sym_COLON,
      sym_identifier,
  [1952] = 6,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(9), 1,
      anon_sym_type,
    ACTIONS(11), 1,
      sym_export_modifier,
    ACTIONS(151), 1,
      ts_builtin_sym_end,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    STATE(75), 2,
      sym_type_definition,
      aux_sym_source_file_repeat1,
  [1973] = 6,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(60), 1,
      anon_sym_QMARK,
    ACTIONS(64), 1,
      anon_sym_AMP,
    ACTIONS(68), 1,
      anon_sym_PIPE,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(153), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1994] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(126), 1,
      sym_identifier,
    ACTIONS(155), 1,
      anon_sym_RBRACE,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    STATE(71), 3,
      sym_field,
      sym_method,
      aux_sym_object_type_repeat1,
  [2013] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(126), 1,
      sym_identifier,
    ACTIONS(157), 1,
      anon_sym_RBRACE,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    STATE(74), 3,
      sym_field,
      sym_method,
      aux_sym_object_type_repeat1,
  [2032] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(159), 5,
      anon_sym_COMMA,
      anon_sym_EQ_GT,
      anon_sym_RBRACE,
      anon_sym_COLON,
      sym_identifier,
  [2047] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(163), 1,
      anon_sym_COMMA,
    ACTIONS(165), 1,
      anon_sym_COLON,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(161), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [2065] = 6,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(167), 1,
      anon_sym_QMARK,
    ACTIONS(169), 1,
      anon_sym_LPAREN,
    ACTIONS(171), 1,
      anon_sym_COLON,
    STATE(83), 1,
      sym_parameters,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
  [2085] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(173), 1,
      anon_sym_COMMA,
    STATE(85), 1,
      aux_sym_generic_arguments_repeat1,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(96), 2,
      anon_sym_GT,
      anon_sym_RPAREN,
  [2103] = 6,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(17), 1,
      anon_sym_RPAREN,
    ACTIONS(21), 1,
      sym_self,
    ACTIONS(176), 1,
      sym_identifier,
    STATE(98), 1,
      sym_parameter,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
  [2123] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(88), 1,
      anon_sym_COMMA,
    ACTIONS(178), 1,
      anon_sym_RPAREN,
    STATE(85), 1,
      aux_sym_generic_arguments_repeat1,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
  [2140] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(88), 1,
      anon_sym_COMMA,
    ACTIONS(180), 1,
      anon_sym_GT,
    STATE(85), 1,
      aux_sym_generic_arguments_repeat1,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
  [2157] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(182), 1,
      anon_sym_EQ,
    ACTIONS(184), 1,
      anon_sym_LT,
    STATE(120), 1,
      sym_generic_parameters,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
  [2174] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(186), 1,
      anon_sym_COMMA,
    ACTIONS(189), 1,
      anon_sym_GT,
    STATE(90), 1,
      aux_sym_generic_parameters_repeat1,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
  [2191] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(88), 1,
      anon_sym_COMMA,
    ACTIONS(191), 1,
      anon_sym_RPAREN,
    STATE(85), 1,
      aux_sym_generic_arguments_repeat1,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
  [2208] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(193), 1,
      anon_sym_COMMA,
    ACTIONS(195), 1,
      anon_sym_GT,
    STATE(97), 1,
      aux_sym_generic_parameters_repeat1,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
  [2225] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(21), 1,
      sym_self,
    ACTIONS(176), 1,
      sym_identifier,
    STATE(107), 1,
      sym_parameter,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
  [2242] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(23), 1,
      sym_identifier,
    STATE(110), 1,
      sym__type_identifier,
    STATE(111), 1,
      sym_generic_parameter,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
  [2259] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(197), 1,
      anon_sym_COMMA,
    ACTIONS(199), 1,
      anon_sym_RPAREN,
    STATE(96), 1,
      aux_sym_parameters_repeat1,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
  [2276] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(201), 1,
      anon_sym_COMMA,
    ACTIONS(204), 1,
      anon_sym_RPAREN,
    STATE(96), 1,
      aux_sym_parameters_repeat1,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
  [2293] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(193), 1,
      anon_sym_COMMA,
    ACTIONS(206), 1,
      anon_sym_GT,
    STATE(90), 1,
      aux_sym_generic_parameters_repeat1,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
  [2310] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(197), 1,
      anon_sym_COMMA,
    ACTIONS(208), 1,
      anon_sym_RPAREN,
    STATE(95), 1,
      aux_sym_parameters_repeat1,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
  [2327] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(184), 1,
      anon_sym_LT,
    ACTIONS(210), 1,
      anon_sym_EQ,
    STATE(121), 1,
      sym_generic_parameters,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
  [2344] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(23), 1,
      sym_identifier,
    STATE(92), 1,
      sym_generic_parameter,
    STATE(110), 1,
      sym__type_identifier,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
  [2361] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(88), 1,
      anon_sym_COMMA,
    ACTIONS(212), 1,
      anon_sym_GT,
    STATE(85), 1,
      aux_sym_generic_arguments_repeat1,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
  [2378] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(214), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [2390] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(216), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [2402] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(25), 1,
      sym_identifier,
    STATE(44), 1,
      sym__type_identifier,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
  [2416] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(218), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [2428] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(23), 1,
      sym_identifier,
    STATE(27), 1,
      sym__type_identifier,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
  [2442] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(204), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2454] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(84), 1,
      anon_sym_COLON,
    ACTIONS(220), 1,
      anon_sym_QMARK,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
  [2468] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(23), 1,
      sym_identifier,
    STATE(99), 1,
      sym__type_identifier,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
  [2482] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(222), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [2494] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(189), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [2506] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(23), 1,
      sym_identifier,
    STATE(89), 1,
      sym__type_identifier,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
  [2520] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(224), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [2532] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
    ACTIONS(226), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2544] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(228), 1,
      anon_sym_COLON,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
  [2555] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(230), 1,
      anon_sym_EQ_GT,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
  [2566] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(232), 1,
      anon_sym_COLON,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
  [2577] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(234), 1,
      anon_sym_EQ,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
  [2588] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(236), 1,
      anon_sym_EQ,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
  [2599] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(238), 1,
      anon_sym_EQ,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
  [2610] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(240), 1,
      anon_sym_EQ,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
  [2621] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(242), 1,
      anon_sym_type,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
  [2632] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(244), 1,
      anon_sym_EQ_GT,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
  [2643] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(246), 1,
      ts_builtin_sym_end,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_block_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 48,
  [SMALL_STATE(4)] = 96,
  [SMALL_STATE(5)] = 135,
  [SMALL_STATE(6)] = 174,
  [SMALL_STATE(7)] = 213,
  [SMALL_STATE(8)] = 252,
  [SMALL_STATE(9)] = 291,
  [SMALL_STATE(10)] = 330,
  [SMALL_STATE(11)] = 369,
  [SMALL_STATE(12)] = 408,
  [SMALL_STATE(13)] = 447,
  [SMALL_STATE(14)] = 486,
  [SMALL_STATE(15)] = 525,
  [SMALL_STATE(16)] = 564,
  [SMALL_STATE(17)] = 603,
  [SMALL_STATE(18)] = 642,
  [SMALL_STATE(19)] = 681,
  [SMALL_STATE(20)] = 720,
  [SMALL_STATE(21)] = 759,
  [SMALL_STATE(22)] = 798,
  [SMALL_STATE(23)] = 824,
  [SMALL_STATE(24)] = 846,
  [SMALL_STATE(25)] = 872,
  [SMALL_STATE(26)] = 898,
  [SMALL_STATE(27)] = 923,
  [SMALL_STATE(28)] = 944,
  [SMALL_STATE(29)] = 963,
  [SMALL_STATE(30)] = 982,
  [SMALL_STATE(31)] = 1001,
  [SMALL_STATE(32)] = 1020,
  [SMALL_STATE(33)] = 1039,
  [SMALL_STATE(34)] = 1058,
  [SMALL_STATE(35)] = 1079,
  [SMALL_STATE(36)] = 1102,
  [SMALL_STATE(37)] = 1127,
  [SMALL_STATE(38)] = 1146,
  [SMALL_STATE(39)] = 1165,
  [SMALL_STATE(40)] = 1184,
  [SMALL_STATE(41)] = 1207,
  [SMALL_STATE(42)] = 1230,
  [SMALL_STATE(43)] = 1253,
  [SMALL_STATE(44)] = 1275,
  [SMALL_STATE(45)] = 1293,
  [SMALL_STATE(46)] = 1311,
  [SMALL_STATE(47)] = 1333,
  [SMALL_STATE(48)] = 1349,
  [SMALL_STATE(49)] = 1375,
  [SMALL_STATE(50)] = 1397,
  [SMALL_STATE(51)] = 1419,
  [SMALL_STATE(52)] = 1441,
  [SMALL_STATE(53)] = 1465,
  [SMALL_STATE(54)] = 1487,
  [SMALL_STATE(55)] = 1511,
  [SMALL_STATE(56)] = 1535,
  [SMALL_STATE(57)] = 1551,
  [SMALL_STATE(58)] = 1567,
  [SMALL_STATE(59)] = 1583,
  [SMALL_STATE(60)] = 1599,
  [SMALL_STATE(61)] = 1615,
  [SMALL_STATE(62)] = 1631,
  [SMALL_STATE(63)] = 1649,
  [SMALL_STATE(64)] = 1669,
  [SMALL_STATE(65)] = 1691,
  [SMALL_STATE(66)] = 1713,
  [SMALL_STATE(67)] = 1729,
  [SMALL_STATE(68)] = 1745,
  [SMALL_STATE(69)] = 1771,
  [SMALL_STATE(70)] = 1797,
  [SMALL_STATE(71)] = 1823,
  [SMALL_STATE(72)] = 1842,
  [SMALL_STATE(73)] = 1857,
  [SMALL_STATE(74)] = 1876,
  [SMALL_STATE(75)] = 1895,
  [SMALL_STATE(76)] = 1916,
  [SMALL_STATE(77)] = 1937,
  [SMALL_STATE(78)] = 1952,
  [SMALL_STATE(79)] = 1973,
  [SMALL_STATE(80)] = 1994,
  [SMALL_STATE(81)] = 2013,
  [SMALL_STATE(82)] = 2032,
  [SMALL_STATE(83)] = 2047,
  [SMALL_STATE(84)] = 2065,
  [SMALL_STATE(85)] = 2085,
  [SMALL_STATE(86)] = 2103,
  [SMALL_STATE(87)] = 2123,
  [SMALL_STATE(88)] = 2140,
  [SMALL_STATE(89)] = 2157,
  [SMALL_STATE(90)] = 2174,
  [SMALL_STATE(91)] = 2191,
  [SMALL_STATE(92)] = 2208,
  [SMALL_STATE(93)] = 2225,
  [SMALL_STATE(94)] = 2242,
  [SMALL_STATE(95)] = 2259,
  [SMALL_STATE(96)] = 2276,
  [SMALL_STATE(97)] = 2293,
  [SMALL_STATE(98)] = 2310,
  [SMALL_STATE(99)] = 2327,
  [SMALL_STATE(100)] = 2344,
  [SMALL_STATE(101)] = 2361,
  [SMALL_STATE(102)] = 2378,
  [SMALL_STATE(103)] = 2390,
  [SMALL_STATE(104)] = 2402,
  [SMALL_STATE(105)] = 2416,
  [SMALL_STATE(106)] = 2428,
  [SMALL_STATE(107)] = 2442,
  [SMALL_STATE(108)] = 2454,
  [SMALL_STATE(109)] = 2468,
  [SMALL_STATE(110)] = 2482,
  [SMALL_STATE(111)] = 2494,
  [SMALL_STATE(112)] = 2506,
  [SMALL_STATE(113)] = 2520,
  [SMALL_STATE(114)] = 2532,
  [SMALL_STATE(115)] = 2544,
  [SMALL_STATE(116)] = 2555,
  [SMALL_STATE(117)] = 2566,
  [SMALL_STATE(118)] = 2577,
  [SMALL_STATE(119)] = 2588,
  [SMALL_STATE(120)] = 2599,
  [SMALL_STATE(121)] = 2610,
  [SMALL_STATE(122)] = 2621,
  [SMALL_STATE(123)] = 2632,
  [SMALL_STATE(124)] = 2643,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(114),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type_path, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type_identifier, 1, 0, 1),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qualified_type, 2, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_qualified_type_repeat1, 2, 0, 0),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_qualified_type_repeat1, 2, 0, 0), SHIFT_REPEAT(106),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type, 1, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_type, 3, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_type, 2, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_optional_type, 2, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_type, 2, 0, 3),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_type, 3, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_intersection_type, 3, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_type, 3, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_type, 3, 0, 6),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_type, 4, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_arguments, 3, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_arguments, 4, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_qualified_type_repeat1, 2, 0, 0), SHIFT_REPEAT(104),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym__type_identifier, 1, 0, 1), SHIFT(117),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_definition, 5, 0, 5),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_definition, 6, 0, 7),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_generic_arguments_repeat1, 2, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 3, 0, 8),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_definition, 4, 0, 2),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 4, 0, 9),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method, 4, 0, 10),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_definition, 5, 0, 4),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 4, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [134] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_object_type_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_type_repeat1, 2, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [141] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(109),
  [144] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(122),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 3, 0, 8),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 3, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 4, 0, 9),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 2, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method, 2, 0, 3),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [173] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_generic_arguments_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [176] = {.entry = {.count = 1, .reusable = false}}, SHIFT(108),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [186] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_generic_parameters_repeat1, 2, 0, 0), SHIFT_REPEAT(94),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_generic_parameters_repeat1, 2, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [201] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2, 0, 0), SHIFT_REPEAT(93),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method, 3, 0, 3),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 4, 0, 8),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method, 5, 0, 10),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_parameter, 1, 0, 3),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 5, 0, 9),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 1, 0, 0),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_parameters, 3, 0, 0),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_parameters, 4, 0, 0),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [246] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_luab(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
