---@meta
-- Renderer-local types.
--
-- No imports and no vendored copy: `geometry.Drawable` is ambient here
-- because renderer depends on the `geometry` package, whose own
-- `[types] defs = ["geometry"]` publishes those classes into every dependent's
-- ambient scope (the luals `workspace.library` model, #108). The class names
-- live in one global namespace across the workspace and its libraries, so
-- `geometry.Drawable` resolves exactly as a local class would.
--
-- A filled square rendered as ASCII art. The side is a cell count, so it is
-- an `integer` — `string.rep("#", self.side)` typechecks against the
-- stdlib's `integer` count parameter. The concrete carrier in
-- src/square.lua reopens this class name, same merge-by-name idiom as
-- ../geometry/src/circle.lua.
---@class render.Square : geometry.Drawable
---@field side integer
