---@meta
-- 2D geometry primitives and the shapes they satisfy — LuaCATS ambient
-- definitions.
--
-- This is a `.d.lua` definition package: a `---@meta` module wired in via
-- `[types] defs = ["geometry"]` in luabox.toml (the file stem `geometry`
-- names the package, same mechanism as `love-asteroids-lite`'s
-- `defs/love2d.d.lua`). Every type declared here is ambient to this
-- package's own files — no imports, addressed by plain name. See
-- ../README.md for a tour of the LuaCATS features this example exercises.

--- A point in 2D space. `label` is an optional caption; `unit` is an
--- optional coordinate unit (see the `geometry.Unit` alias below).
---
--- OPERATOR OVERLOADS (#114): a Point adds and subtracts componentwise, so
--- `p + q` and `p - q` are declared to yield another `geometry.Point`. luabox
--- APPLIES these during inference (luals parity): the result of `+`/`-` on two
--- points types as `geometry.Point` — not `unknown` — so binding it to a
--- `---@type geometry.Point` checks clean and misusing it (feeding the result
--- to a `string`, say) is a real `luabox check` error. See
--- ../src/shapes_data.lua for a typed use.
---@class geometry.Point
---@field x number
---@field y number
---@field label? string
---@field unit? geometry.Unit
---@operator add(geometry.Point): geometry.Point
---@operator sub(geometry.Point): geometry.Point

--- Anything with an area and a perimeter, described as a method-shaped
--- `---@class` (an "interface" by convention).
---
--- CONFORMANCE (#107): this IS a verified contract. A carrier declaring
--- `: geometry.Shape` (see ../src/circle.lua and ../src/rect.lua) must
--- actually implement `area`/`perimeter`/`my_static` with compatible
--- signatures, or `luabox check` reports LB0300 at the carrier's `---@class`
--- annotation — real structural conformance on the LuaCATS path. (Declaring
--- the interface here in the `---@meta` def carries no obligation of its own:
--- defs are contracts, not carriers.)
---@class geometry.Shape
---@field area fun(self): number
---@field perimeter fun(self): number
---@field my_static fun(): number

--- A Shape that can also render itself as text. Declared as an extension
--- (`: geometry.Shape`).
---@class geometry.Drawable : geometry.Shape
---@field draw fun(self): string

--- The circle carrier's declared shape. The concrete carrier in
--- ../src/circle.lua reopens this same class name on `local Circle = {}`;
--- luabox merges the two declarations, so `self.radius` there resolves to
--- `number` from the `---@field` below even though circle.lua repeats only
--- the class name and its `: geometry.Shape` extension.
---@class geometry.Circle : geometry.Shape
---@field radius number

--- The rect carrier's declared shape (see geometry.Circle above).
---@class geometry.Rect : geometry.Shape
---@field width number
---@field height number

-- A homogeneous pair — a REAL generic `---@class<T>` (#84). Both fields are
-- typed by the parameter `T`, and a reference substitutes it per use site:
-- `---@type geometry.Pair<number>` gives `first`/`second` the type `number`,
-- `geometry.Pair<string>` gives them `string`, and nesting works
-- (`geometry.Pair<geometry.Pair<number>>`). See ../src/shapes_data.lua for a
-- typed instance and ../README.md for the exact `luabox check` error a misuse
-- produces, verified against the real binary. (This matches
-- lua-language-server's generic-class semantics — ecosystem parity, not a
-- luabox extension. A bare `geometry.Pair` with no type arguments stays
-- lenient, exactly as luals treats it.)
---@class geometry.Pair<T>
---@field first T
---@field second T

--- The unit a coordinate or label is expressed in — a closed string-literal
--- union. `---@alias` IS enforced: passing anything outside the union at an
--- annotated position is a real `luabox check` error (see ../src/shapes_data.lua).
---@alias geometry.Unit "px"|"pt"
