//! `luabox.lock` — deterministic, text-based lockfile (SPEC.md §5, §6).
//!
//! Cargo.lock-shaped: a `version = 1` header and a `[[package]]` array.
//! Serialization is *canonical*: entries sorted by name, then version, then
//! source; fixed key order; fixed formatting. Two identical resolutions
//! therefore produce byte-identical files, and `parse ∘ serialize` is the
//! identity on canonical text (round-trip tests below; SPEC.md §16.2
//! determinism invariants live in `tests/proptests.rs`).
//!
//! Entry shape:
//!
//! ```toml
//! version = 1
//!
//! [[package]]
//! name = "penlight"
//! version = "1.14.0"
//! source = "registry"
//! checksum = "sha256:…"
//! dependencies = ["luafilesystem"]
//! ```
//!
//! The root project's own entry carries no `source`/`checksum` (it *is*
//! the tree being resolved), mirroring Cargo.lock. `source` strings are
//! `registry` (checksums arrive with #20), `git+<url>#<commit>` (the
//! *resolved* commit sha, pinned by `GitProvider` even for tag/branch
//! refs), or `path+<root-relative path>`.

use std::fmt;

use semver::Version;
use toml_edit::{Array, ArrayOfTables, DocumentMut, Item, Table, value};

/// Current lockfile format version (the `version = …` header).
pub const LOCKFILE_VERSION: u64 = 1;

/// The lockfile's on-disk name.
pub const LOCKFILE_NAME: &str = "luabox.lock";

const HEADER: &str =
    "# This file is @generated by luabox.\n# It is not intended for manual editing.\n";

/// Where a locked package came from. `None` on a [`LockedPackage`] means
/// the root project itself.
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum LockedSource {
    /// The first-party registry (SPEC.md §6).
    Registry,
    /// A git source: `url#commit`, where `commit` is the resolved sha
    /// (falling back to the symbolic reference for providers that cannot
    /// pin one).
    Git { spec: String },
    /// An http(s)/local tarball source, recorded as `url+<url>`. The
    /// integrity digest travels in the entry's `checksum` (`sha256:…`).
    Url { url: String },
    /// A path/workspace dependency, root-relative with forward slashes.
    Path { path: String },
}

impl fmt::Display for LockedSource {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Registry => write!(f, "registry"),
            Self::Git { spec } => write!(f, "git+{spec}"),
            Self::Url { url } => write!(f, "url+{url}"),
            Self::Path { path } => write!(f, "path+{path}"),
        }
    }
}

impl LockedSource {
    fn parse(text: &str) -> Result<Self, LockfileError> {
        if text == "registry" {
            Ok(Self::Registry)
        } else if let Some(spec) = text.strip_prefix("git+") {
            Ok(Self::Git {
                spec: spec.to_owned(),
            })
        } else if let Some(url) = text.strip_prefix("url+") {
            Ok(Self::Url {
                url: url.to_owned(),
            })
        } else if let Some(path) = text.strip_prefix("path+") {
            Ok(Self::Path {
                path: path.to_owned(),
            })
        } else {
            Err(LockfileError::new(format!(
                "unknown package source `{text}` (expected `registry`, `git+…`, `url+…`, or `path+…`)"
            )))
        }
    }
}

/// One `[[package]]` entry.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub struct LockedPackage {
    pub name: String,
    pub version: Version,
    /// `None` for the root project entry.
    pub source: Option<LockedSource>,
    /// `sha256:…` placeholder until the registry (#20) supplies real ones.
    pub checksum: Option<String>,
    /// Names of direct dependencies (disambiguated with a version suffix
    /// when the same name resolves from several sources), sorted.
    pub dependencies: Vec<String>,
}

/// A parsed (or freshly resolved) `luabox.lock`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Lockfile {
    pub version: u64,
    /// Canonically sorted; [`Lockfile::new`] enforces the ordering.
    pub packages: Vec<LockedPackage>,
}

impl Lockfile {
    /// Builds a lockfile in canonical order from unsorted entries.
    #[must_use]
    pub fn new(mut packages: Vec<LockedPackage>) -> Self {
        packages.sort();
        Self {
            version: LOCKFILE_VERSION,
            packages,
        }
    }

    /// Looks up an entry by name (first match in canonical order).
    #[must_use]
    pub fn get(&self, name: &str) -> Option<&LockedPackage> {
        self.packages.iter().find(|p| p.name == name)
    }

    /// Canonical TOML text. Deterministic: same lockfile, same bytes.
    #[must_use]
    pub fn to_toml_string(&self) -> String {
        let mut doc = DocumentMut::new();
        doc.insert(
            "version",
            value(i64::try_from(self.version).unwrap_or(i64::MAX)),
        );
        let mut tables = ArrayOfTables::new();
        for package in &self.packages {
            let mut table = Table::new();
            table.decor_mut().set_prefix("\n");
            table.insert("name", value(&package.name));
            table.insert("version", value(package.version.to_string()));
            if let Some(source) = &package.source {
                table.insert("source", value(source.to_string()));
            }
            if let Some(checksum) = &package.checksum {
                table.insert("checksum", value(checksum));
            }
            if !package.dependencies.is_empty() {
                let deps: Array = package.dependencies.iter().map(String::as_str).collect();
                table.insert("dependencies", value(deps));
            }
            tables.push(table);
        }
        doc.insert("package", Item::ArrayOfTables(tables));
        format!("{HEADER}{doc}")
    }

    /// Parses lockfile text. Unknown keys are tolerated (forward
    /// compatibility); a missing/foreign `version` header is not.
    pub fn parse(text: &str) -> Result<Self, LockfileError> {
        let doc: DocumentMut = text
            .parse()
            .map_err(|e| LockfileError::new(format!("invalid TOML: {e}")))?;
        let version = doc
            .get("version")
            .and_then(Item::as_integer)
            .ok_or_else(|| LockfileError::new("missing `version` header"))?;
        let version = u64::try_from(version)
            .map_err(|_| LockfileError::new(format!("invalid lockfile version {version}")))?;
        if version != LOCKFILE_VERSION {
            return Err(LockfileError::new(format!(
                "unsupported lockfile version {version} (this luabox supports version {LOCKFILE_VERSION})"
            )));
        }

        let mut packages = Vec::new();
        if let Some(item) = doc.get("package") {
            let tables = item.as_array_of_tables().ok_or_else(|| {
                LockfileError::new("`package` must be an array of tables (`[[package]]`)")
            })?;
            for table in tables {
                packages.push(parse_package(table)?);
            }
        }
        Ok(Self {
            version,
            packages: Self::new(packages).packages,
        })
    }
}

fn parse_package(table: &Table) -> Result<LockedPackage, LockfileError> {
    let name = table
        .get("name")
        .and_then(Item::as_str)
        .ok_or_else(|| LockfileError::new("[[package]] entry is missing `name`"))?
        .to_owned();
    let version_text = table
        .get("version")
        .and_then(Item::as_str)
        .ok_or_else(|| LockfileError::new(format!("package `{name}` is missing `version`")))?;
    let version = Version::parse(version_text).map_err(|e| {
        LockfileError::new(format!(
            "package `{name}` has invalid version `{version_text}`: {e}"
        ))
    })?;
    let source = match table.get("source") {
        None => None,
        Some(item) => {
            let text = item.as_str().ok_or_else(|| {
                LockfileError::new(format!("package `{name}`: `source` must be a string"))
            })?;
            Some(LockedSource::parse(text)?)
        }
    };
    let checksum = match table.get("checksum") {
        None => None,
        Some(item) => Some(
            item.as_str()
                .ok_or_else(|| {
                    LockfileError::new(format!("package `{name}`: `checksum` must be a string"))
                })?
                .to_owned(),
        ),
    };
    let dependencies = match table.get("dependencies") {
        None => Vec::new(),
        Some(item) => {
            let array = item.as_array().ok_or_else(|| {
                LockfileError::new(format!(
                    "package `{name}`: `dependencies` must be an array of strings"
                ))
            })?;
            let mut deps = Vec::with_capacity(array.len());
            for entry in array {
                deps.push(
                    entry
                        .as_str()
                        .ok_or_else(|| {
                            LockfileError::new(format!(
                                "package `{name}`: `dependencies` must be an array of strings"
                            ))
                        })?
                        .to_owned(),
                );
            }
            deps
        }
    };
    Ok(LockedPackage {
        name,
        version,
        source,
        checksum,
        dependencies,
    })
}

/// A lockfile parse/validation failure.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LockfileError {
    pub message: String,
}

impl LockfileError {
    fn new(message: impl Into<String>) -> Self {
        Self {
            message: message.into(),
        }
    }
}

impl fmt::Display for LockfileError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "invalid {LOCKFILE_NAME}: {}", self.message)
    }
}

impl std::error::Error for LockfileError {}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> Lockfile {
        Lockfile::new(vec![
            LockedPackage {
                name: "zed".to_owned(),
                version: Version::new(2, 0, 0),
                source: Some(LockedSource::Registry),
                checksum: Some("sha256:beef".to_owned()),
                dependencies: vec![],
            },
            LockedPackage {
                name: "app".to_owned(),
                version: Version::new(0, 1, 0),
                source: None,
                checksum: None,
                dependencies: vec!["local-lib".to_owned(), "zed".to_owned()],
            },
            LockedPackage {
                name: "local-lib".to_owned(),
                version: Version::new(1, 0, 0),
                source: Some(LockedSource::Path {
                    path: "libs/local-lib".to_owned(),
                }),
                checksum: None,
                dependencies: vec![],
            },
        ])
    }

    #[test]
    fn serializes_sorted_and_canonical() {
        let text = sample().to_toml_string();
        let expected = "\
# This file is @generated by luabox.
# It is not intended for manual editing.
version = 1

[[package]]
name = \"app\"
version = \"0.1.0\"
dependencies = [\"local-lib\", \"zed\"]

[[package]]
name = \"local-lib\"
version = \"1.0.0\"
source = \"path+libs/local-lib\"

[[package]]
name = \"zed\"
version = \"2.0.0\"
source = \"registry\"
checksum = \"sha256:beef\"
";
        assert_eq!(text, expected);
    }

    #[test]
    fn round_trips_value_and_bytes() {
        let lock = sample();
        let text = lock.to_toml_string();
        let reparsed = Lockfile::parse(&text).expect("canonical text parses");
        assert_eq!(reparsed, lock);
        // Byte-identical re-serialization: serialize ∘ parse ∘ serialize.
        assert_eq!(reparsed.to_toml_string(), text);
    }

    #[test]
    fn parse_sorts_noncanonical_input() {
        let text = "version = 1\n\n[[package]]\nname = \"zzz\"\nversion = \"1.0.0\"\nsource = \"registry\"\n\n[[package]]\nname = \"aaa\"\nversion = \"1.0.0\"\nsource = \"registry\"\n";
        let lock = Lockfile::parse(text).expect("parses");
        assert_eq!(lock.packages[0].name, "aaa");
        assert_eq!(lock.packages[1].name, "zzz");
    }

    #[test]
    fn rejects_unsupported_version_and_bad_entries() {
        assert!(Lockfile::parse("version = 99\n").is_err());
        assert!(Lockfile::parse("").is_err());
        assert!(
            Lockfile::parse("version = 1\n\n[[package]]\nversion = \"1.0.0\"\n").is_err(),
            "missing name"
        );
        assert!(
            Lockfile::parse("version = 1\n\n[[package]]\nname = \"a\"\nversion = \"not-semver\"\n")
                .is_err()
        );
        assert!(
            Lockfile::parse(
                "version = 1\n\n[[package]]\nname = \"a\"\nversion = \"1.0.0\"\nsource = \"carrier-pigeon+coop\"\n"
            )
            .is_err()
        );
    }

    #[test]
    fn git_and_path_sources_round_trip() {
        for source in [
            LockedSource::Git {
                spec: "https://example.com/r.git#abc123".to_owned(),
            },
            LockedSource::Url {
                url: "https://example.com/mylib-1.0.tar.gz".to_owned(),
            },
            LockedSource::Path {
                path: "../sibling".to_owned(),
            },
            LockedSource::Registry,
        ] {
            let text = source.to_string();
            assert_eq!(LockedSource::parse(&text).expect("parses"), source);
        }
    }
}
