#!/bin/bash
# Self-test for scripts/perf-gate.sh and scripts/perf-gate-lib.sh.
#
# Two halves, two different costs.
#
# Part 1 (perf-gate-lib.sh's pure functions: budget arithmetic, "was the
# corpus actually generated", the manifest writer) runs in milliseconds —
# no release build, no real `luabox`. This is the split every gate-with-
# real-judgement self-test in this repo uses (scripts/tests/mutants-gate.sh,
# scripts/tests/luals-differential.sh): the expensive step is not what a
# self-test needs to prove wrong, the JUDGEMENT around it is.
#
# Part 2 runs scripts/perf-gate.sh ITSELF, for real, against a stub
# `luabox`/`gen-corpus` whose timing and peak RSS this file controls exactly
# (via LUABOX_BIN/GEN_CORPUS_BIN — see perf-gate.sh's own comment on that
# seam). #58 review round 6, M28: the previous version of this file only
# ever exercised perf-gate-lib.sh in isolation, plus a four-string `grep -qF`
# on perf-gate.sh's TEXT standing in for "the lib is actually wired in".
# Reproduced directly against that grep before this rewrite: neutering any
# one of perf-gate.sh's ten threshold comparisons (`<` -> a constant true),
# deleting any of its eight legs outright, widening RSS_BUDGET_MIB 300 ->
# 300000 in perf-gate-budgets.env, or deleting the `RAYON_NUM_THREADS=4`
# pin around the retained-TypeEnv leg — left the self-test 14/14 green. Part
# 2 below runs the real script, with the real threshold comparisons, the
# real budget constants (no per-leg env override; if a budget widens, the
# case built to sit just over the REAL default now sits under a wider one
# and its expected FAIL silently disappears) and the real corpus-generation
# code paths (gen-corpus is stubbed to create files instantly; the
# retained-TypeEnv and diagnostics-heavy corpora are generated by
# perf-gate.sh's own bash/awk, unstubbed) — only the two things that make a
# release build+run expensive (compiling `luabox`, and its own real CPU/RSS
# cost) are swapped out. Each case below drives exactly ONE leg over its
# real budget while every other leg stays fast and light, and asserts that
# leg's FAIL line is present, every OTHER leg's FAIL line is absent, and the
# overall exit code is 1 — proving each comparison is individually
# load-bearing, not merely that "something in the script can still fail".
#
# Every case in both halves was checked directly against the file(s) it
# pins: the named line(s) removed or neutered, this file re-run, the
# failure confirmed, the line restored. This costs real seconds per
# behavioural case (a release-speed `sleep`/RSS-allocation, still no
# `cargo build`) rather than the milliseconds Part 1 or the sibling
# gate-selftests manage — a stated, deliberate trade for behavioural proof
# over the prior text-grep, following exactly the guidance this repo's own
# review left at #58 round 6, M28's remediation and decisions/12 §2's
# "verified by mutation" rule.
#
#   bash scripts/tests/perf-gate-selftest.sh
set -u

here="$(cd "$(dirname "$0")" && pwd)"
repo="$here/../.."
lib="$repo/scripts/perf-gate-lib.sh"
gate="$repo/scripts/perf-gate.sh"

# shellcheck source=../perf-gate-lib.sh
source "$lib"
# shellcheck source=selftest-lib.sh
source "$here/selftest-lib.sh"

# ============================================================================
# Part 1 — perf-gate-lib.sh's pure functions. Milliseconds, no real binary.
# ============================================================================

# --- scale_budget_ms --------------------------------------------------------
# The float multiply every timed leg's budget goes through — pinned at the
# exact factor values this repo actually uses: 1.0 (default), the CI
# multiplier (4.0, ci.yml's perf-gates job), and this box's own multiplier
# (5.0, needed here because this machine is CPU-starved for the pre-existing
# timing legs — see scripts/perf-gate.sh's Env: block).
check "scale_budget_ms default factor" "$(scale_budget_ms 1000 1.0)" "1000"
check "scale_budget_ms CI factor (4.0)" "$(scale_budget_ms 1000 4.0)" "4000"
check "scale_budget_ms this box's factor (5.0)" "$(scale_budget_ms 4000 5.0)" "20000"
# The two cases above (1.5 * 50 = 75.0, 1.999 * 1000 = 1999.0) land on exact
# integers in double precision — truncation and round-to-nearest print the
# identical digit, so neither one actually pins "%d" (truncate) over "%.0f"
# (round-to-nearest); verified by swapping printf's format and watching all
# five cases stay green. A case that discriminates the two needs a product
# whose fractional part clears .5 by a comfortable margin (so IEEE-754
# imprecision near the boundary itself can't flip the result either way):
# 100 * 1.678 = 167.8 (%d -> 167, %.0f -> 168) and 1000 * 1.9999 = 1999.9
# (%d -> 1999, %.0f -> 2000) — both checked directly against the %.0f
# mutation described above and confirmed to fail under it.
check "scale_budget_ms truncates, does not round" "$(scale_budget_ms 100 1.678)" "167"
check "scale_budget_ms truncates a fractional result down" "$(scale_budget_ms 1000 1.9999)" "1999"

# The optional ceiling (local merge-gate finding on round 6's budget rebase):
# LUABOX_PERF_FACTOR multiplies a base that already carries ~3x headroom, so
# CI's effective ceiling for the check leg had reached ~12x its measured
# baseline. The cap bounds that. A leg passing no ceiling must be unchanged —
# the cases above are that control.
check "scale_budget_ms caps a scaled budget at its ceiling" \
    "$(scale_budget_ms 7500 4.0 8000)" "8000"
check "scale_budget_ms leaves a scaled budget under its ceiling alone" \
    "$(scale_budget_ms 7500 1.0 8000)" "7500"
check "scale_budget_ms ceiling equal to the scaled value does not cap" \
    "$(scale_budget_ms 2000 2.0 4000)" "4000"
check "scale_budget_ms with an empty ceiling behaves as if uncapped" \
    "$(scale_budget_ms 1000 4.0 "")" "4000"

# --- assert_lua_file_count --------------------------------------------------
# N38's exact fix: the leg this backs (RETAINED-TYPEENV REGRESSION GATE)
# used to print "PASS ... 11 MiB < 100 MiB" against an empty corpus with
# nothing catching it — reproduced here directly rather than through a full
# perf-gate.sh run.
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

mkdir -p "$work/full"
for i in 1 2 3; do : >"$work/full/mod_$i.lua"; done
check_true "assert_lua_file_count passes on a matching corpus" \
    assert_lua_file_count "$work/full" 3

mkdir -p "$work/empty"
check_false "assert_lua_file_count fails on an empty corpus (N38's exact shape)" \
    assert_lua_file_count "$work/empty" 500

mkdir -p "$work/short"
for i in 1 2; do : >"$work/short/mod_$i.lua"; done
check_false "assert_lua_file_count fails on a truncated corpus" \
    assert_lua_file_count "$work/short" 3

# The error message must name what it found and what it expected — a
# self-test that only checks the exit code would pass just as happily if
# this collapsed to a bare `return 1` with no diagnostic at all.
msg="$(assert_lua_file_count "$work/short" 3 2>&1 >/dev/null)"
case "$msg" in
*"has 2 .lua file(s), expected 3"*) echo "PASS  assert_lua_file_count reports the actual and expected counts"; pass=$((pass + 1)) ;;
*)
    echo "FAIL  assert_lua_file_count reports the actual and expected counts: got [$msg]" >&2
    fail=$((fail + 1))
    ;;
esac

# Non-.lua files in the same directory must not be counted — a corpus
# generator that also drops its own luabox.toml (every one of them does)
# must not inflate the count and mask a truncated .lua run.
mkdir -p "$work/mixed"
for i in 1 2 3; do : >"$work/mixed/mod_$i.lua"; done
: >"$work/mixed/luabox.toml"
: >"$work/mixed/README.md"
check_true "assert_lua_file_count ignores non-.lua files in the same directory" \
    assert_lua_file_count "$work/mixed" 3

# --- write_perf_manifest ----------------------------------------------------
# N42: three call sites in perf-gate.sh (and two in perf-gate.ps1's
# New-PerfManifest) used to hand-copy this heredoc with one bit of drift
# possible per copy — the package name, and whether [types] is present.
strict_out="$work/strict.toml"
write_perf_manifest "$strict_out" "perf-gate-corpus" "true"
if grep -qF 'name = "perf-gate-corpus"' "$strict_out" \
    && grep -qF '[types]' "$strict_out" \
    && grep -qF 'strict = true' "$strict_out" \
    && tail -1 "$strict_out" | grep -qF '[dependencies]'; then
    echo "PASS  write_perf_manifest (strict) has the right name, [types] block and trailing [dependencies]"
    pass=$((pass + 1))
else
    echo "FAIL  write_perf_manifest (strict): unexpected content" >&2
    sed 's/^/        /' "$strict_out" >&2
    fail=$((fail + 1))
fi

lenient_out="$work/lenient.toml"
write_perf_manifest "$lenient_out" "perf-gate-diagnostics" "false"
if grep -qF 'name = "perf-gate-diagnostics"' "$lenient_out" \
    && ! grep -qF '[types]' "$lenient_out" \
    && ! grep -qF 'strict = true' "$lenient_out" \
    && tail -1 "$lenient_out" | grep -qF '[dependencies]'; then
    echo "PASS  write_perf_manifest (non-strict) omits [types] entirely"
    pass=$((pass + 1))
else
    echo "FAIL  write_perf_manifest (non-strict): unexpected content" >&2
    sed 's/^/        /' "$lenient_out" >&2
    fail=$((fail + 1))
fi

# The generated manifest must be parseable TOML, not merely visually
# plausible — catches a stray quote or an unescaped brace the string-based
# assertions above would not. `tomllib` is stdlib-only from Python 3.11;
# SKIP rather than FAIL below that, the same "a missing tool is not evidence
# of a regression" rule scripts/perf-gate.sh's own peak-RSS leg follows for
# a missing python3 entirely.
if python3 -c 'import tomllib' >/dev/null 2>&1; then
    if python3 - "$strict_out" <<'PYEOF'
import sys
import tomllib
with open(sys.argv[1], "rb") as f:
    data = tomllib.load(f)
assert data["package"]["name"] == "perf-gate-corpus"
assert data["types"]["strict"] is True
PYEOF
    then
        echo "PASS  write_perf_manifest (strict) output parses as valid TOML"
        pass=$((pass + 1))
    else
        echo "FAIL  write_perf_manifest (strict) output does not parse as valid TOML" >&2
        fail=$((fail + 1))
    fi
else
    echo "SKIP  write_perf_manifest (strict) TOML-validity check — no python3 tomllib (needs 3.11+)"
fi

# ============================================================================
# Part 2 — scripts/perf-gate.sh, run for real against a stub luabox.
# ============================================================================
#
# The stub understands four subcommands (--version, fmt, check, lint) and
# decides which of perf-gate.sh's eight legs is asking by $PWD, which is
# unique per leg (perf-gate.sh always `cd`s into a leg-specific directory
# before invoking the binary): the ~100-kLOC corpus root, its
# retained-env/ subdirectory, and the four diagnostics-heavy/{lint,check,
# lint-rendered,check-rendered} subdirectories. Every knob is an env var so
# each case below can drive exactly one leg slow/heavy while every other
# stays fast — STUB_*_S in (fractional) seconds for `sleep`, STUB_*_RSS_MIB
# for the two memory legs, where the stub `exec`s into a one-line python3
# process that allocates and touches that many MiB before exiting (`exec`,
# not a subshell, so the allocation is attributed to the exact process
# scripts/peak-rss.py waits on — a subshell's usage would not be).
if [ -n "${PERF_GATE_SELFTEST_SKIP_BEHAVIORAL:-}" ]; then
    echo "SKIP  Part 2 (behavioural perf-gate.sh runs) — PERF_GATE_SELFTEST_SKIP_BEHAVIORAL set"
else

gwork="$(mktemp -d)"
trap 'rm -rf "$work" "$gwork"' EXIT
mkdir -p "$gwork/bin"

stub_luabox="$gwork/bin/luabox"
cat >"$stub_luabox" <<'STUB'
#!/bin/bash
set -u
cmd="${1:-}"
here="$PWD"

alloc() {
    # $1: seconds to sleep first (may be fractional or empty/0); $2: MiB to
    # allocate and actually touch (so the pages are really committed, not
    # just reserved) before exiting. exec'd, not forked, so peak-rss.py's
    # RUSAGE_CHILDREN measurement (of THIS process, across whatever it
    # execs into) captures it.
    exec python3 -c "
import time
time.sleep(${1:-0})
mib = ${2:-1}
buf = bytearray(mib * 1024 * 1024)
for i in range(0, len(buf), 4096):
    buf[i] = 1
"
}

case "$cmd" in
--version)
    sleep "${STUB_VERSION_S:-0}"
    exit 0
    ;;
fmt)
    sleep "${STUB_FMT_S:-0}"
    exit 1 # a synthetic corpus is not guaranteed canonical; harmless, perf-gate.sh ignores this rc
    ;;
lint)
    case "$here" in
    */diagnostics-heavy/lint) sleep "${STUB_DIAG_LINT_S:-0}" ;;
    */diagnostics-heavy/lint-rendered) sleep "${STUB_DIAG_LINT_RENDERED_S:-0}" ;;
    *) sleep 0 ;;
    esac
    exit 1
    ;;
check)
    case "$here" in
    */retained-env)
        rss="${STUB_RETAINED_RSS_MIB:-1}"
        if [ "${RAYON_NUM_THREADS:-}" != "4" ] && [ -n "${STUB_RETAINED_RSS_MIB_UNPINNED:-}" ]; then
            rss="$STUB_RETAINED_RSS_MIB_UNPINNED"
        fi
        alloc "${STUB_RETAINED_S:-0}" "$rss"
        ;;
    */diagnostics-heavy/check)
        sleep "${STUB_DIAG_CHECK_S:-0}"
        exit 1
        ;;
    */diagnostics-heavy/check-rendered)
        sleep "${STUB_DIAG_CHECK_RENDERED_S:-0}"
        exit 1
        ;;
    *)
        alloc "${STUB_CHECK_100K_S:-0}" "${STUB_CHECK_100K_RSS_MIB:-1}"
        ;;
    esac
    ;;
*)
    echo "stub-luabox: unsupported invocation: $*" >&2
    exit 2
    ;;
esac
STUB
chmod +x "$stub_luabox"

stub_gen_corpus="$gwork/bin/gen-corpus"
cat >"$stub_gen_corpus" <<'STUB'
#!/bin/bash
# Understands only --out <dir> --files <n> (the one shape perf-gate.sh
# invokes it with) and creates exactly that many empty .lua files instantly
# — real content is irrelevant here, only the COUNT assert_lua_file_count
# checks and the stub luabox's own subcommand dispatch (which never reads
# .lua contents for the 100-kLOC corpus) matter.
set -u
out="" files=0
prev=""
for arg in "$@"; do
    case "$prev" in
    --out) out="$arg" ;;
    --files) files="$arg" ;;
    esac
    prev="$arg"
done
mkdir -p "$out"
i=0
while [ "$i" -lt "$files" ]; do
    : >"$out/mod_$i.lua"
    i=$((i + 1))
done
STUB
chmod +x "$stub_gen_corpus"

# The full set of FAIL lines a healthy run of every leg could print — used
# below to assert absence of every leg's FAIL EXCEPT the one case under
# test is targeting, so a case cannot pass by accident because it asserted
# the right exit code and the right FAIL line while some OTHER comparison
# also (wrongly) fired or a leg silently swapped places with another.
all_fail_needles=(
    "FAIL cold start:"
    "FAIL fmt --check (warm):"
    "FAIL check (warm):"
    "FAIL check peak RSS:"
    "FAIL retained-TypeEnv regression, peak RSS:"
    "FAIL retained-TypeEnv regression, wall time:"
    "FAIL lint (diagnostics-heavy):"
    "FAIL check (diagnostics-heavy):"
    "FAIL lint (diagnostics-heavy, rendered):"
    "FAIL check (diagnostics-heavy, rendered):"
)

# run_gate <name> <want-exit> <extra-needle>...
# Invokes perf-gate.sh for real (LUABOX_BIN/GEN_CORPUS_BIN pointed at the
# stubs above, so no cargo build and no real corpus-generation binary), at
# the REAL default budgets (no LUABOX_PERF_FACTOR, no *_BUDGET_MIB
# override) — a case's STUB_* env vars (set by the caller before invoking
# this) decide which leg, if any, goes over budget. want_fail_needle (may
# be empty) is the ONE "FAIL ..." line expected present; every OTHER member
# of all_fail_needles is asserted absent automatically.
run_gate() {
    local name="$1" want_exit="$2" want_fail_needle="${3:-}"
    shift 2
    [ $# -gt 0 ] && shift
    local log="$gwork/$name.log"
    LUABOX_BIN="$stub_luabox" GEN_CORPUS_BIN="$stub_gen_corpus" \
        bash "$gate" >"$log" 2>&1
    local got=$?
    local needles=("$@")
    if [ -n "$want_fail_needle" ]; then
        needles+=("$want_fail_needle")
    fi
    local n
    for n in "${all_fail_needles[@]}"; do
        [ -n "$want_fail_needle" ] && [ "$n" = "$want_fail_needle" ] && continue
        needles+=("!$n")
    done
    assert_exit "$name" "$want_exit" "$got" "$log" "${needles[@]}"
}

# --- baseline: every leg fast and light -> ALL GATES PASSED, exit 0 --------
# Also the case that proves the stub luabox/gen-corpus and the LUABOX_BIN/
# GEN_CORPUS_BIN seam actually wire perf-gate.sh's own corpus-generation
# code (the retained-env 500-file loop, the four diagnostics-heavy awk
# generators, both write_perf_manifest call sites, both assert_lua_file_count
# call sites) for real — none of that is stubbed, only the binaries are.
unset STUB_VERSION_S STUB_FMT_S STUB_CHECK_100K_S STUB_CHECK_100K_RSS_MIB \
    STUB_RETAINED_S STUB_RETAINED_RSS_MIB STUB_RETAINED_RSS_MIB_UNPINNED \
    STUB_DIAG_LINT_S STUB_DIAG_CHECK_S STUB_DIAG_LINT_RENDERED_S STUB_DIAG_CHECK_RENDERED_S
export STUB_CHECK_100K_RSS_MIB=5 STUB_RETAINED_RSS_MIB=5
run_gate all_legs_pass_when_fast_and_light 0 "" "ALL GATES PASSED" "!GATES FAILED"

# --- one case per threshold comparison: exactly that leg's FAIL, nothing
# else -----------------------------------------------------------------
# Every case below leaves every OTHER leg at the baseline's fast/light
# values (STUB_CHECK_100K_RSS_MIB / STUB_RETAINED_RSS_MIB stay small unless
# a case is specifically about one of the RSS legs) and drives exactly one
# real comparison over its REAL budget from perf-gate-budgets.env (or
# perf-gate.sh's own hardcoded retained-env defaults) — not an
# env-overridden one, so a mutation that WIDENS the underlying constant
# (#58 review round 6, M28's literal example: RSS_BUDGET_MIB 300 -> 300000)
# makes the case's chosen value fall back under the new, wider budget and
# the case goes RED, exactly like a deleted leg or a neutered `<` would.

# 1. cold start — 50ms budget (COLD_START_BUDGET_BASE_MS), 10 runs of
#    `--version` each sleeping past it.
STUB_VERSION_S=0.2 run_gate cold_start_threshold_is_live 1 "FAIL cold start:"
unset STUB_VERSION_S

# 2. fmt --check (warm) — 2000ms budget (FMT_BUDGET_BASE_MS).
STUB_FMT_S=3 run_gate fmt_threshold_is_live 1 "FAIL fmt --check (warm):"
unset STUB_FMT_S

# 3. check (warm) — CHECK_BUDGET_BASE_MS (perf-gate-budgets.env; rebased by
#    #58 review round 6, M37 to 7500ms with real headroom — see that file's
#    comment). Sleep well past it.
STUB_CHECK_100K_S=8 run_gate check_warm_threshold_is_live 1 "FAIL check (warm):"
unset STUB_CHECK_100K_S

# 4. check peak RSS — 300 MiB budget (RSS_BUDGET_MIB). This is the exact
#    M28 mutation ("widening rss_budget_mib 300 -> 300000") reproduced as a
#    live case: 310 MiB only fails against the REAL 300 MiB default.
STUB_CHECK_100K_RSS_MIB=310 run_gate check_peak_rss_threshold_is_live 1 "FAIL check peak RSS:"
STUB_CHECK_100K_RSS_MIB=5

# 5. retained-TypeEnv regression, peak RSS — 100 MiB budget (perf-gate.sh's
#    own hardcoded default, no dedicated env var set here).
STUB_RETAINED_RSS_MIB=150 run_gate retained_env_rss_threshold_is_live 1 "FAIL retained-TypeEnv regression, peak RSS:"
STUB_RETAINED_RSS_MIB=5

# 6. retained-TypeEnv regression, wall time — 4000ms budget
#    (retained_env_check_budget_base_ms).
STUB_RETAINED_S=5 run_gate retained_env_wall_time_threshold_is_live 1 "FAIL retained-TypeEnv regression, wall time:"
unset STUB_RETAINED_S

# 7-10. the four diagnostics-heavy legs — 1200/4000/600/2400ms budgets
#       (DIAG_LINT_BUDGET_BASE_MS / DIAG_CHECK_BUDGET_BASE_MS /
#       DIAG_LINT_RENDERED_BUDGET_BASE_MS / DIAG_CHECK_RENDERED_BUDGET_BASE_MS
#       — DIAG_CHECK_BUDGET_BASE_MS also rebased by M37 above, to 4000ms).
STUB_DIAG_LINT_S=1.5 run_gate diag_lint_threshold_is_live 1 "FAIL lint (diagnostics-heavy):"
unset STUB_DIAG_LINT_S

STUB_DIAG_CHECK_S=4.5 run_gate diag_check_threshold_is_live 1 "FAIL check (diagnostics-heavy):"
unset STUB_DIAG_CHECK_S

STUB_DIAG_LINT_RENDERED_S=1 run_gate diag_lint_rendered_threshold_is_live 1 "FAIL lint (diagnostics-heavy, rendered):"
unset STUB_DIAG_LINT_RENDERED_S

STUB_DIAG_CHECK_RENDERED_S=3 run_gate diag_check_rendered_threshold_is_live 1 "FAIL check (diagnostics-heavy, rendered):"
unset STUB_DIAG_CHECK_RENDERED_S

# --- M29: the RAYON_NUM_THREADS=4 pin around the retained-TypeEnv leg is
# now proven BEHAVIOURALLY, not by grepping for the string
# "RAYON_NUM_THREADS=4" (which three code COMMENTS above the leg already
# satisfy on their own, with the actual pin deleted). The stub's RSS for
# the retained-env corpus is LOW when it sees RAYON_NUM_THREADS=4 (what
# perf-gate.sh is supposed to pin around that one call) and HIGH otherwise
# — set here to simulate "the ambient/wide value leaked through because the
# pin is gone". The self-test's OWN shell exports RAYON_NUM_THREADS=16
# (deliberately not 4, and not left to whatever this box's real core count
# happens to be, so the case is portable) before invoking the gate: with
# the pin intact, perf-gate.sh's own `RAYON_NUM_THREADS=4 "$luabox_bin"
# check ...` overrides that ambient value for the one command it wraps, the
# stub sees "4", reports the LOW RSS, and the leg PASSES. Delete the pin
# (mutants-gate.sh's own class of mutation, applied here to perf-gate.sh)
# and the ambient 16 leaks through unchanged, the stub reports the HIGH
# RSS, and this exact case goes RED.
# The stub's own python3 interpreter has a baseline RSS of ~11-12 MiB on
# this box before it allocates anything, so the PASS case's measured MiB
# figure is not a fixed, predictable number — assert the PASS/FAIL verdict
# line, not an exact byte count. 5 MiB requested (pinned) stays far under
# the 100 MiB budget once that baseline is added; 150 MiB requested
# (unpinned) clears it by ~50%, comfortably beyond interpreter noise either
# way.
STUB_RETAINED_RSS_MIB=5 STUB_RETAINED_RSS_MIB_UNPINNED=150 \
    RAYON_NUM_THREADS=16 \
    run_gate retained_env_rayon_pin_is_live 0 "" "PASS retained-TypeEnv regression, peak RSS:"
unset STUB_RETAINED_RSS_MIB_UNPINNED
STUB_RETAINED_RSS_MIB=5

fi # PERF_GATE_SELFTEST_SKIP_BEHAVIORAL

selftest_report "perf-gate-selftest"
